max_width = 100
hard_tabs = false
tab_spaces = 4
newline_style = "Unix"
use_small_heuristics = "Max"
indent_style = "Block"
reorder_imports = true
reorder_modules = true
remove_nested_import_grouping = false
use_field_init_shorthand = true
use_try_shorthand = true
format_code_in_doc_comments = true
format_strings = true
wrap_comments = true
comment_width = 80
normalize_comments = true
normalize_doc_attributes = true
license_template_path = "LICENSE"
# unstable_features = true # Uncomment if using nightly
